# docker-compose.yml
services:
  qrbot:
    build: .
    container_name: qrbot_almaz

    # host:container — приложение в контейнере слушает 8080,
    # снаружи будет доступно на http://<SERVER-IP>:5005
    ports:
      - "5005:8080"

    # реальные ключи лежат в .env рядом с этим файлом
    env_file:
      - .env

    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "1"

    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3