# docker-compose.yml
version: "3.9"

services:
  qrbot:
    build: .
    container_name: qrbot_almaz
    # приложение внутри всё так же слушает 8080
    expose:                       # заменяет 'ports:' — наружу не торчит
      - "8080"
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "1"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  caddy:
    image: caddy:2.8-alpine        # официальная
    container_name: caddy_reverse_proxy
    restart: unless-stopped
    ports:
      - "8081:8081"                   # HTTP → автоперенаправление на HTTPS
      - "8443:8443"                 # HTTPS выдаёт сертификат
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro   # конфиг
      - caddy_data:/data                       # certmagic storage
      - caddy_config:/config                   # сессии, OCSP cache
    depends_on:
      - qrbot                                # сначала поднимается backend

volumes:
  caddy_data:
  caddy_config: