# Docker Compose v2 – field "version" больше не нужен

networks:
  qr_net:
  caddy_net:
    external: true     # создаётся стеком Caddy

# ------------------------------------------------------------------------
#  Якорь с единым образом: собираем один раз, используем в 4 сервисах
# ------------------------------------------------------------------------
x-qr-image: &qr_image
  build: .
  image: qr-bot-almaz:latest      # тег для reuse
  env_file: .env
  restart: unless-stopped
  networks: [qr_net]

services:
  # ---------- WEB ------------------------------------------------------
  web:
    <<: *qr_image
    container_name: qrbot_web
    command: >
      gunicorn -w 2 -k gthread -t 30 -b 0.0.0.0:8080 web.main:app
    expose: ["8080"]            # наружу не публикуем
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks: [qr_net, caddy_net]
    # если Caddy должен подняться раньше — раскомментируйте:
    # depends_on:
    #   caddy_reverse_proxy:
    #     condition: service_started

  # ---------- BOT ------------------------------------------------------
  bot:
    <<: *qr_image
    container_name: qrbot_bot
    command: python -u bot/bot.py

  # ---------- TAMAGOTCHI SCHEDULER -------------------------------------
  tamagotchi_scheduler:
    <<: *qr_image
    container_name: qrbot_tamagotchi
    command: python -u schedulers/tamagotchi_scheduler.py

  # ---------- AUTO-CLOSE SCHEDULER -------------------------------------
  auto_close_scheduler:
    <<: *qr_image
    container_name: qrbot_autoclose
    command: python -u schedulers/auto_close_scheduler.py