name: Deploy QR-BOT_ALMAZ

on:
  push:
    branches: [ main ]

# ▸ один деплой за раз
concurrency:
  group: deploy-qrbot-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ───────── 1. Код репозитория ─────────
    - name: Checkout source
      # 👇 фиксируем конкретную минор-версию
      uses: actions/checkout@v4.1.2

    # ───────── 2. Подключаемся по SSH и деплоим ─────────
    - name: Deploy on VPS
      # 👇 тоже фиксированная версия
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || '22' }}
        # чтобы смена host-key не роняла билд
        host_fingerprint: ${{ secrets.SERVER_FINGERPRINT }}

        # ──────── shell-скрипт, выполняемый на сервере ────────
        script: |
          set -Eeuo pipefail

          PROJECT_DIR="$HOME/qr-bot-almaz"
          REPO_URL="https://github.com/${{ github.repository }}"

          echo "== Проверяем / клонируем проект =="
          if [[ ! -d "$PROJECT_DIR/.git" ]]; then
            git clone "$REPO_URL" "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          echo "== Обновляем код (без уничтожения локальных правок) =="
          git fetch origin main --tags

          # Есть ли локальные изменения во tracked-файлах?
          if ! git diff-index --quiet HEAD; then
            echo "::error::В репозитории есть непушеные изменения! Деплой остановлен."
            git status -s
            exit 1
          fi

          # Fast-forward merge, без reset --hard
          git merge --ff-only origin/main

          echo "== Проверяем .env =="
          if [[ ! -f .env ]]; then
            echo "::error::.env не найден. Скопируйте его вручную перед деплоем."
            exit 1
          fi

          echo "== Останавливаем старый стек =="
          docker compose down || true

          echo "== Собираем / тянем образы =="

          # ▸ Вариант А. Строим образ прямо на сервере (оставить если так удобнее)
          docker compose build --pull

          # ▸ Вариант Б. Если образы собираются и публикуются в GHCR / Docker Hub
          # docker compose pull || true

          echo "== Запускаем контейнеры =="
          docker compose up -d --remove-orphans

          echo "== Post-деплой health-check =="
          # ждём максимум 30 сек, пока сервис отдаст 200/OK
          for i in {1..30}; do
            if curl -sf http://localhost:5005/ >/dev/null; then
              echo "Service healthy 👌"
              ok=1
              break
            fi
            sleep 1
          done
          [[ "${ok:-0}" == "1" ]] || {
            echo "::error::Контейнер не отвечает на health-check"
            docker compose ps
            docker compose logs --tail=100
            exit 1
          }

          echo "== Чистим старые dangling-образы (не моложе 24 ч) =="
          docker image prune -af --filter "until=24h" || true